In [37]:
import nltk
import pandas as pd

In [39]:
nltk.download_shell()

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Downloader>  l

Packages:
  [ ] abc................. Australian Broadcasting Commission 2006
  [ ] alpino.............. Alpino Dutch Treebank
  [ ] averaged_perceptron_tagger Averaged Perceptron Tagger
  [ ] averaged_perceptron_tagger_eng Averaged Perceptron Tagger (JSON)
  [ ] averaged_perceptron_tagger_ru Averaged Perceptron Tagger (Russian)
  [ ] averaged_perceptron_tagger_rus Averaged Perceptron Tagger (Russian)
  [ ] basque_grammars..... Grammars for Basque
  [ ] bcp47............... BCP-47 Language Tags
  [ ] biocreative_ppi..... BioCreAtIvE (Critical Assessment of Information
                           Extraction Systems in Biology)
  [ ] bllip_wsj_no_aux.... BLLIP Parser: WSJ Model
  [ ] book_grammars....... Grammars from NLTK Book
  [ ] brown............... Brown Corpus
  [ ] brown_tei........... Brown Corpus (TEI XML Version)
  [ ] cess_cat............ CESS-CAT Treebank
  [ ] cess_esp............ CESS-ESP Treebank
  [ ] chat80.............. Chat-80 Data Files
  [ ] city_database....... City Database
  [ ] cmudict............. The Carnegie Mellon Pronouncing Dictionary (0.6)
  [ ] comparative_sentences Comparative Sentence Dataset

Hit Enter to continue:  q

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------

Downloader>  q

In [40]:
messages=[line.rstrip() for line in open('/home/oem/Downloads/spam.csv',encoding="latin-1")]

In [41]:
print(len(messages))

5575

In [42]:
messages[0]

'v1,v2,,,'

In [43]:
for mess_no,message in enumerate(messages[:10]):
  print(mess_no,message)
  print('/n')

0 v1,v2,,,
/n
1 ham,"Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...",,,
/n
2 ham,Ok lar... Joking wif u oni...,,,
/n
3 spam,Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's,,,
/n
4 ham,U dun say so early hor... U c already then say...,,,
/n
5 ham,"Nah I don't think he goes to usf, he lives around here though",,,
/n
6 spam,"FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv",,,
/n
7 ham,Even my brother is not like to speak with me. They treat me like aids patent.,,,
/n
8 ham,As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune,,,
/n
9 spam,WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.,,,
/n

In [44]:
messages[0]
{"type":"string"}

{'type': 'string'}

In [47]:
import pandas as pd

In [48]:
messages=pd.read_csv('/home/oem/Downloads/spam.csv',sep='\t',names=['label','message'],encoding="latin-1")

In [49]:
messages.head()

                                               label  message
0                                           v1,v2,,,      NaN
1  ham,"Go until jurong point, crazy.. Available ...      NaN
2               ham,Ok lar... Joking wif u oni...,,,      NaN
3  spam,Free entry in 2 a wkly comp to win FA Cup...      NaN
4  ham,U dun say so early hor... U c already then...      NaN

In [50]:
#convert string into vector format
import string

In [51]:
#remove punctuations and stopwords
mess="sample message ! Notice: it has punctation."

In [52]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [53]:
nopunc=[c for c in mess if c not in string.punctuation ]

In [54]:
nopunc

['s',
 'a',
 'm',
 'p',
 'l',
 'e',
 ' ',
 'm',
 'e',
 's',
 's',
 'a',
 'g',
 'e',
 ' ',
 ' ',
 'N',
 'o',
 't',
 'i',
 'c',
 'e',
 ' ',
 'i',
 't',
 ' ',
 'h',
 'a',
 's',
 ' ',
 'p',
 'u',
 'n',
 'c',
 't',
 'a',
 't',
 'i',
 'o',
 'n']

In [55]:
nopunc=''.join(nopunc)

In [56]:
nopunc

'sample message  Notice it has punctation'

In [57]:
#remove stopwords
from nltk.corpus import stopwords

In [58]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /home/oem/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [59]:
nopunc.split()

['sample', 'message', 'Notice', 'it', 'has', 'punctation']

In [60]:
clean_mess=[word for word in nopunc.split() if word.lower() not in stopwords.words("english")]

In [61]:
clean_mess

['sample', 'message', 'Notice', 'punctation']

In [62]:
#apply to actual dataset
def text_process(mess):
  nopunc=[char for char in mess if char not in string.punctuation]
  nopunc="".join(nopunc)
  return[word for word in nopunc.split() if word.lower() not in stopwords.words("english")]
messages.head()

                                               label  message
0                                           v1,v2,,,      NaN
1  ham,"Go until jurong point, crazy.. Available ...      NaN
2               ham,Ok lar... Joking wif u oni...,,,      NaN
3  spam,Free entry in 2 a wkly comp to win FA Cup...      NaN
4  ham,U dun say so early hor... U c already then...      NaN

In [10]:
import pandas as pd
df= pd.read_csv("/home/oem/Downloads/spam.csv",encoding="latin-1")
df=df.rename(columns={
     "v1": "label",
     "v2": "message"
     })

df=df[["label","message"]]

print(df.head())

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [16]:
#CONVERTING into vectors
from sklearn.feature_extraction.text import CountVectorizer
bow_transformer = CountVectorizer().fit(df['message'])
df_bow = bow_transformer.transform(df['message'])

In [13]:
print(len(bow_transformer.vocabulary_))

8672

In [26]:
mess4 = df['message'][6]
print(mess4)

Even my brother is not like to speak with me. They treat me like aids patent.

In [29]:
bow4 = bow_transformer.transform([mess4])

In [31]:
print(bow4)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 14 stored elements and shape (1, 8672)>
  Coords	Values
  (0, 992)	1
  (0, 1722)	1
  (0, 2998)	1
  (0, 4206)	1
  (0, 4615)	2
  (0, 4939)	2
  (0, 5223)	1
  (0, 5405)	1
  (0, 5722)	1
  (0, 7112)	1
  (0, 7653)	1
  (0, 7756)	1
  (0, 7863)	1
  (0, 8433)	1

In [38]:
bow_transformer.get_feature_names_out()[7000]

smoking

In [42]:
messages_bow  = bow_transformer.transform(df['message'])

In [44]:
print('shape of the Sparse Matrix:',messages_bow.shape)

shape of the Sparse Matrix: (5572, 8672)

In [45]:
#check how many nonzero occurences
messages_bow.nnz

73916

In [46]:
#difference between TF and DF
#TF is frequency counter for a term t in document d.
#DF is the count of occurences of term t in the documents set N
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer=TfidfTransformer().fit(messages_bow)
tfidf4=tfidf_transformer.transform(bow4)
print(tfidf4)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14 stored elements and shape (1, 8672)>
  Coords	Values
  (0, 992)	0.39931890051255087
  (0, 1722)	0.29420339994257655
  (0, 2998)	0.247272320868778
  (0, 4206)	0.13442219946765846
  (0, 4615)	0.3747940151467183
  (0, 4939)	0.27656964172621945
  (0, 5223)	0.14345267447581758
  (0, 5405)	0.1610340098593331
  (0, 5722)	0.39931890051255087
  (0, 7112)	0.2726633877547696
  (0, 7653)	0.21741778421846686
  (0, 7756)	0.0982833859221388
  (0, 7863)	0.3036497276132227
  (0, 8433)	0.1684331406442322

In [47]:
#converting the whole bag of words into tfidf
messages_tfidf = tfidf_transformer.transform(messages_bow)

In [51]:
from sklearn.naive_bayes import MultinomialNB

spam_detect_model = MultinomialNB().fit(messages_tfidf, df['label'])

In [52]:
all_pred = spam_detect_model.predict(messages_tfidf)
all_pred

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'],
      shape=(5572,), dtype='<U4')

In [54]:
from sklearn.model_selection import train_test_split

msg_train, msg_test, label_train, label_test = train_test_split(
    df['message'], df['label'], test_size=0.2, random_state=42
)

spam_detect_model = MultinomialNB()
spam_detect_model.fit(messages_tfidf, df['label'])

predict = spam_detect_model.predict(messages_tfidf)

from sklearn.metrics import classification_report

print(classification_report(df['label'], predict))

              precision    recall  f1-score   support

         ham       0.97      1.00      0.99      4825
        spam       1.00      0.82      0.90       747

    accuracy                           0.98      5572
   macro avg       0.99      0.91      0.94      5572
weighted avg       0.98      0.98      0.98      5572

In [56]:
from sklearn.model_selection import train_test_split
msg_train,msg_test,label_test,label_train = \
train_test_split(df['message'],df['label'],test_size=0.2)

In [59]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report

# Split the data
msg_train, msg_test, label_train, label_test = train_test_split(
    df['message'],
    df['label'],
    test_size=0.2,
    random_state=42
)
# Create pipeline
pipeline = Pipeline([
    ('bow', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('classifier', MultinomialNB())
])

# Train the model
pipeline.fit(msg_train, label_train)

# Predict test data
predictions = pipeline.predict(msg_test)

# Classification report
print(classification_report(label_test, predictions))

              precision    recall  f1-score   support

         ham       0.96      1.00      0.98       965
        spam       1.00      0.72      0.84       150

    accuracy                           0.96      1115
   macro avg       0.98      0.86      0.91      1115
weighted avg       0.96      0.96      0.96      1115

In [61]:
from sklearn import model_selection, naive_bayes, svm
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer
from sklearn.metrics import accuracy_score, classification_report

# Create SVM pipeline
pipeline1 = Pipeline([
    ('bow', CountVectorizer()),
    ('tfidf', TfidfTransformer()),
    ('classifier', svm.SVC(C=1.0, kernel='linear'))
])

# Train the model
pipeline1.fit(msg_train, label_train)

# Predict test data
predictions1 = pipeline1.predict(msg_test)

# Accuracy
print("Accuracy:", accuracy_score(label_test, predictions1))

# Classification report
print(classification_report(label_test, predictions1))

Accuracy: 0.9829596412556054
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       0.99      0.89      0.93       150

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115